[package]
name = "hiewlm-plugin-zip"
description = "hiewLM container plugin: ZIP archive structure and member listing."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
hiewlm-core = { path = "../hiewlm-core" }

[lints]
workspace = true
